The tilde `+~+` is aliased to the current user’s home directory. To test
out some applications of this, change directories to the root directory
of the system:

[source,bash]
----
cd /
----

The `+~+` alias works in any case where you have to specify a path. If
you wanted to list the contents of the _openscap_data_ subdirectory
located in the home directory of *root*, the following command is valid:

[source,bash]
----
ls ~/openscap_data
----

____
_NOTE:_ This is another place where you can practice tab completion.
Typing `+ls ~/op+` and then pressing tab will complete the path for you
since there is nothing else in *root*’s home directory starting with
`+op+`.
____

This means that running `+cd ~+` will always change directories to the
home directory of the user that you are logged in as.

[source,bash]
----
cd ~
----

You will see that your current directory has changed from

to

____
_NOTE:_ The `+cd+` command contains yet another shortcut, where running
`+cd+` without any arguments will behave the same as running `+cd ~+`.
____

Print the full path to the directory you are currently in, the `+~+`
directory, using the "`print working directory`" command:

[source,bash]
----
pwd
----

This shows that `+~+` is equivalent to `+/root+`, the home directory for
the *root* user. Try the same test for a different user account on this
system, *rhel*. Switch to *rhel* in the second terminal tab:

[source,bash]
----
su - rhel
----

Adding the `+-+` after `+su+` will automatically change directories into
the *rhel* user’s home directory, so print the full directory again:

[source,bash]
----
pwd
----

You can see that when logged in as *rhel*, `+~+` is equivalent to
`+/home/rhel+`, which is the *rhel* user’s home directory.

____
_NOTE:_ The *root* user home directory is in a unique location,
`+/root+`. All other users’ home directories will be located following
the convention `+/home/<username>+`, as in the case of the *rhel* user’s
home directory.
____
