Any file or directory that begins with a `+.+` in the name will be
interpreted as hidden, and will only show up when using the `+-a+`
option with `+ls+`.

List the files in your current directory:

[source,bash]
----
ls
----

Now, try it again with the `+-a+` option. Many more files and
directories will show up, even though you have not changed where you are
looking.

[source,bash]
----
ls -a
----

Adding the `+-a+` option reveals that there are numerous hidden files
and directories in this home directory. These are hidden because they
are not files that you would interact with often, so there is no need
for them to clutter up *root*’s home directory visually. However, they
are data that is associated with the user, so it is beneficial from an
organization point of view to store them in the home directory
associated with their specific user.

____
_NOTE_: One common hidden directory you will commonly run into is the
`+.git+` directory. This is part of any git repository and stores data
used in version control for your local repository.
____

Creating a new hidden file or directory is quite simple, just start the
name with a `+.+`

[source,bash]
----
touch .hidden-file
----

Now that this file is created, confirm that it only shows up when using
`+ls -a+`:

[source,bash]
----
ls
----

[source,bash]
----
ls -a
----
