=== Running commands as root vs using sudo

*root* is the name of the administrator account.
This account has the highest amount of control of any account on the system.
 If a person has the root password, they can access and make changes to any part of the system.

`sudo`, on the other hand, is a command which allows non-root users to
perform administrative tasks. Users in the _wheel_ group have access to
the `sudo` command.

NOTE: When logged in as *root*, the character in the command prompt is
`#`. When you switch users to *rhel*, this character changes to `$`.
*root* will always be symbolized by `#` to give you the warning that any
command you enter will be run with the highest level of administrative
privileges.


Use the `su` command to switch to the *rhel* user:

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
su - rhel
----

This command has no expected output, however the cli prompt will change to reflect your user.

.Command
[source,text]
----
[rhel@rhel ~]$
----

Then, try to access the following file:

NOTE: The below command is expected to fail with a "Permission Denied" error

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
cat /etc/shadow
----

.Output
[source,text,subs="+macros,+attributes"]
----
cat: /etc/shadow: Permission denied
----

This configuration file’s permissions prevent *rhel* from reading its
contents. However, *rhel* is part of the _wheel_ group, so you can
circumvent this permissions issue temporarily by prepending `sudo` to
your previous command:

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
sudo cat /etc/shadow
----

.Output
[source,text,subs="+macros,+attributes"]
----
root:$6$rounds=656000$JqES2ILUQte.Kup/$A6dM3Gg0b3WZzZ1wpr6jmyjGB7Ne2AsTGBOSmtKsWjnkcnBtI0qaON6qqXqwXFM/iWZUddUFg/IJTNDl5cBgs0:19970:0:99999:7:::
bin:*:19760:0:99999:7:::
daemon:*:19760:0:99999:7:::
adm:*:19760:0:99999:7:::

<< OUTPUT ABRIDGED >>
----

`sudo` allowed you to access the contents of the file without changing
the associated permissions.

NOTE: `sudo !!` is a shortcut for rerunning the previous command with
`sudo`

Assuming the system is properly configured, most users should not need
to regularly use `sudo` during day-to-day usage. This command should
only be necessary when making administrative changes. If you plan to
make lots of administrative changes, it can save you some time to log in
as *root*. However, the administrative block can act as a safeguard in
the case that you erroneously execute an operation that will modify the
system. Seeing `permission denied` will cause you to double check the
command before re-running it using `sudo`.

